### PR TITLE
TO-DO-LIST-PEER-FEEDBACK-REVIEW PR#1

### PR DESCRIPTION
**Pull request by efmomoh**
In this pull request, I set the repo up and added all the following folders/files:

source ( index.html, index.css, index.js, newFun.js, update.js)
dist folder
README.md
Webpack config file
License file
Linters config files
And eslint packages

### CODE REVIEW

**Review by brighton0102 — CHANGES_REQUESTED** [review]
### Changes Required ♻️
Hi @efmomoh 

- May you kindly please consider documenting your repository in a professional way, it helps future employers and other developers to easily navigate through your repository 👍.

- The code seems relatively well-structured and doesn't appear to have excessive duplication 💯 

- Overall your code looks well-structured and serves its purpose effectively 🚀 

Submit for a re-review when you are done 

Thanks 😀

**Comment by efmomoh** [comment]
> ### Changes Required ♻️
> Hi @efmomoh
> 
> * May you kindly please consider documenting your repository in a professional way, it helps future employers and other developers to easily navigate through your repository 👍.
> * The code seems relatively well-structured and doesn't appear to have excessive duplication 💯
> * Overall your code looks well-structured and serves its purpose effectively 🚀
> 
> Submit for a re-review when you are done
> 
> Thanks 😀

Thank you for the feedback. I will implement it as required, thanks again 👍

**Review by brighton0102 — APPROVED** [review]
Hi @efmomoh 

Good job implementing the requested changes 👍 
Your project is now complete there is nothing else to say other than it's time to merge it.

🎉 🎉🎉🎉🎉🎉

**Comment by efmomoh** [comment]
@brighton0102, thank you for the feedback. I am grateful.

**Pull request merged**
